// src/main/webapp/app/entities/product/product/detail/product-detail.component.ts
import { Component, inject, Input } from '@angular/core';
import { RouterModule } from '@angular/router';

import SharedModule from 'app/shared/shared.module';
import { DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe } from 'app/shared/date';
import { DataUtils } from 'app/core/util/data-util.service';
import { IProduct } from '../product.model';

@Component({
  standalone: true,
  selector: 'jhi-product-detail',
  templateUrl: './product-detail.component.html',
  imports: [SharedModule, RouterModule, DurationPipe, FormatMediumDatetimePipe, FormatMediumDatePipe],
})
export class ProductDetailComponent {
  @Input() product: IProduct | null = null;

  protected dataUtils = inject(DataUtils);

  byteSize(base64String: string): string {
    return this.dataUtils.byteSize(base64String);
  }

  openFile(base64String: string, contentType: string | null | undefined): void {
    this.dataUtils.openFile(base64String, contentType);
  }

  previousState(): void {
    window.history.back();
  }
}

<div class="d-flex justify-content-center">
  <div class="col-8">
    @if (product) {
      <div>
        <h2 data-cy="productDetailsHeading"><span jhiTranslate="storeApp.productProduct.detail.title">Product</span></h2>

        <hr />

        <jhi-alert-error></jhi-alert-error>

        <jhi-alert></jhi-alert>

        <dl class="row-md jh-entity-details">
          <dt><span jhiTranslate="global.field.id">ID</span></dt>
          <dd>
            <span>{{ product.id }}</span>
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.name">Name</span></dt>
          <dd>
            <span>{{ product.name }}</span>
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.description">Description</span></dt>
          <dd>
            <span>{{ product.description }}</span>
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.price">Price</span></dt>
          <dd>
            <span>{{ product.price }}</span>
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.productSize">Product Size</span></dt>
          <dd>
            <span jhiTranslate="{{ 'storeApp.Size.' + product.productSize }}">{{ product.productSize }}</span>
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.image">Image</span></dt>
          <dd>
            @if (product.image) {
              <div>
                <a (click)="openFile(product.image, product.imageContentType)">
                  <img [src]="'data:' + product.imageContentType + ';base64,' + product.image" style="max-width: 100%" alt="product" />
                </a>
                {{ product.imageContentType }}, {{ byteSize(product.image) }}
              </div>
            }
          </dd>
          <dt><span jhiTranslate="storeApp.productProduct.productCategory">Product Category</span></dt>
          <dd>
            @if (product.productCategory) {
              <div>
                <a [routerLink]="['/product-category', product.productCategory.id, 'view']">{{ product.productCategory.name }}</a>
              </div>
            }
          </dd>
        </dl>

        <button type="submit" (click)="previousState()" class="btn btn-info" data-cy="entityDetailsBackButton">
          <fa-icon icon="arrow-left"></fa-icon>&nbsp;<span jhiTranslate="entity.action.back">Back</span>
        </button>

        <button type="button" [routerLink]="['/product', product.id, 'edit']" class="btn btn-primary">
          <fa-icon icon="pencil-alt"></fa-icon>&nbsp;<span jhiTranslate="entity.action.edit">Edit</span>
        </button>
      </div>
    }
  </div>
</div>

// store/src/main/webapp/app/entities/product/product/product-detail.tsx
import React, { useEffect } from 'react';
import { Link, useParams } from 'react-router-dom';
import { Button, Row, Col } from 'reactstrap';
import { Translate, openFile, byteSize } from 'react-jhipster';
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome';

import { useAppDispatch, useAppSelector } from 'app/config/store';

import { getEntity } from './product.reducer';

export const ProductDetail = () => {
  const dispatch = useAppDispatch();

  const { id } = useParams<'id'>();

  useEffect(() => {
    dispatch(getEntity(id));
  }, []);

  const productEntity = useAppSelector(state => state.store.product.entity);
  return (
    <Row>
      <Col md="8">
        <h2 data-cy="productDetailsHeading">
          <Translate contentKey="storeApp.productProduct.detail.title">Product</Translate>
        </h2>
        <dl className="jh-entity-details">
          <dt>
            <span id="id">
              <Translate contentKey="global.field.id">ID</Translate>
            </span>
          </dt>
          <dd>{productEntity.id}</dd>
          <dt>
            <span id="name">
              <Translate contentKey="storeApp.productProduct.name">Name</Translate>
            </span>
          </dt>
          <dd>{productEntity.name}</dd>
          <dt>
            <span id="description">
              <Translate contentKey="storeApp.productProduct.description">Description</Translate>
            </span>
          </dt>
          <dd>{productEntity.description}</dd>
          <dt>
            <span id="price">
              <Translate contentKey="storeApp.productProduct.price">Price</Translate>
            </span>
          </dt>
          <dd>{productEntity.price}</dd>
          <dt>
            <span id="productSize">
              <Translate contentKey="storeApp.productProduct.productSize">Product Size</Translate>
            </span>
          </dt>
          <dd>{productEntity.productSize}</dd>
          <dt>
            <span id="image">
              <Translate contentKey="storeApp.productProduct.image">Image</Translate>
            </span>
          </dt>
          <dd>
            {productEntity.image ? (
              <div>
                {productEntity.imageContentType ? (
                  <a onClick={openFile(productEntity.imageContentType, productEntity.image)}>
                    <img src={`data:${productEntity.imageContentType};base64,${productEntity.image}`} style={{ maxHeight: '30px' }} />
                  </a>
                ) : null}
                <span>
                  {productEntity.imageContentType}, {byteSize(productEntity.image)}
                </span>
              </div>
            ) : null}
          </dd>
          <dt>
            <Translate contentKey="storeApp.productProduct.productCategory">Product Category</Translate>
          </dt>
          <dd>{productEntity.productCategory ? productEntity.productCategory.name : ''}</dd>
        </dl>
        <Button tag={Link} to="/product" replace color="info" data-cy="entityDetailsBackButton">
          <FontAwesomeIcon icon="arrow-left" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.back">Back</Translate>
          </span>
        </Button>
        &nbsp;
        <Button tag={Link} to={`/product/${productEntity.id}/edit`} replace color="primary">
          <FontAwesomeIcon icon="pencil-alt" />{' '}
          <span className="d-none d-md-inline">
            <Translate contentKey="entity.action.edit">Edit</Translate>
          </span>
        </Button>
      </Col>
    </Row>
  );
};

export default ProductDetail;
